### ISSUE TITLE
Parser needs to be tested

### ISSUE THREAD

**Issue by jundl77** [exemplator/exemplator#14]
Sometimes certain functions are not found - this needs to be fixed. 

Currently there are no unit-tests, which is bad. We need to test each scoping-rule to find the bugs and detect future regressions.

Example of errors:
- Method: `set` Type: `java.util.ArrayList`
- Method: `open` Type: `java.io.InputStream`
- Method: `getPlugin` Type: `org.intellimate.izou.addon.AddOnModel`

It seems like only very popular functions are found

**Comment by LeanderK** [comment]
well, this issue is a bit vague ;) I edited it

**Comment by LeanderK** [comment]
@jundl77 do you have examples?

**Comment by jundl77** [comment]
Yes - simple one would be `java.util.ArrayList` with method `set` doesn't work for me.

More interestingly, APIs like [Izou](https://github.com/intellimate/Izou) don't work either.

**Comment by LeanderK** [comment]
I think there are some serious bugs affecting al lot of results. So only very popular methods have a chance of returning something.

**Comment by jundl77** [comment]
yes

**Comment by jundl77** [comment]
I'll look into it in the coming days

**Comment by jundl77** [comment]
So I did some debugging. Code examples are definitely found for those  problem cases (listed above). So I do think there is some bug in the parser. But the other thing is, I have a feeling might not be correctly processing each CompletableFuture that is returned from the code search in the router. I think we may not be correctly waiting for the completion. 

However I could be wrong, as I am not too sure what the `Blocking.get` of Ratpack does.
Anyway, this is the piece of code that I am a bit worried about (it is [here](https://github.com/exemplator/exemplator/blob/master/src/main/java/xyz/exemplator/exemplator/Router.java#L76)): 

``` java
Blocking.get(() -> codeSearch.fetch(searchTerms, request.getPage(), executorService))
                                                .map(futures -> {
                                                    CompletableFuture<Optional<CodeSample>>[] parsedFutures = (CompletableFuture<Optional<CodeSample>>[]) futures.stream()
                                                            .map(future -> future.thenApply(opt ->
                                                                    opt.flatMap(sample ->
                                                                            parseOrReturn(sample, command, request)
                                                                    )
                                                            ))
                                                            .toArray(size -> new CompletableFuture[futures.size()]);

                                                    return CompletableFuture.allOf(parsedFutures)
                                                            .thenApply(v -> Arrays.stream(parsedFutures)
                                                                    .map(CompletableFuture::join)
                                                                    .collect(toList())
                                                            );
                                                })
```

@LeanderK What do you think?

**Comment by jundl77** [comment]
Actually I might not be right about all that, since sometimes it does work. If we weren't waiting for the CompletableFutures correctly. it would probably rarely work if at all.

**Comment by LeanderK** [comment]
hmm looking over it i don't see any bug. But this is hackathon code, so nothing is assured.

**Comment by jundl77** [comment]
what exactly happens in `Blocking.get(() -> codeSearch.fetch(searchTerms, request.getPage(), executorService))`? 

In the Ratpack docs it says the method signature is: `public static <T> Promise<T> get(Factory<T> factory)`

Since when is a List a factory?

**Comment by jundl77** [comment]
Nevermind, I don't understand the code, but it works. :D

**Comment by jundl77** [comment]
Ok - I think I know what the problem is.

There are 2:

#### Problem 1

The parser seems to work fine, it's just that in the first 20 examples found that the search function gives the parser, there are legitimately no matches. For example, an `open` function is used in the same file as an `InputStream`, however the `open` function is not used on the `InputStream` but some other object. 

As a solution, and this goes along with pagination, we should go back and search the next page when no examples are found. 

#### Problem 2

Code that is not very popular (e.g. Izou) is not index by the [search tool](https://searchcode.com/) that we use. The GitHub search API finds it of course. Perhaps we should integrate it in the future somehow (I tried at the hackathon if you remember, but there were some problems with that), but I think for now we should just ignore code that is not indexed.

**Comment by LeanderK** [comment]
I think problem number 1 is a low-hanging fruit. Its not complicated to fix and it needs to be fixed.
Blocking.get just communicates ratpack that its a blocking operation.

**Comment by jundl77** [comment]
Yes - the question now is, how do we handle search times? Do we let the user pick a max. search time? Do we stop after X seconds of searching? And further more, do we parallelize further more by doing the first 2 or 3 pages asynchronously?  Each page is 41 async calls I think. What do you think?

I was thinking we just have a timeout after 1 minute to keep it simple.

**Comment by LeanderK** [comment]
i don't think its smart to let the user handle search times (and i can't think of a web-page that does that). Doing real timeouts in java hard, i would limit the pages. I don't think parallelising makes sense, we are already pretty parallel and we also don't know whether we actually need the results.

**Comment by jundl77** [comment]
Hmm the thing is 2 pages might not be enough, I guess we're just gonna have to test and find a good result/time balance.
